%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/jfoucs/MYGraduationProject/Data

# camera intrinsics
# fr1
camera.fx: 2070.8
camera.fy: 2057.0
camera.cx: 1906.4
camera.cy: 1149.5


# VO paras
number_of_features: 1500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
